pipeline:
  publish:
    image: plugins/docker
    repo: willianvalerio/dd-php
    auto_tag: true
    username:
      from_secret: DOCKER_USERNAME
    password: 
      from_secret: DOCKER_PASSWORD
    when:
      branch:
      - main